### ISSUE TITLE
Not seeing discovery commands - LinuxCNC configuration necessary?

### ISSUE THREAD

**Issue by RaphiePS** [fdarling/mesa-smartserial-device-template#3]
Hello! First off, thanks so much for releasing this, it's enormously helpful for those of us trying some advanced CNC hackery.

I've programmed the Teensy and wired up the SN75179BP to my Mesa 7I76e. The issue is, I'm not seeing any commands in the Teensy serial log - it's as if the Mesa is completely ignoring the RS-422 connection on TB3.

I worried I had miswired it or messed up the Teensy in some way, so I set up a second SN75179BP in a "loopback" configuration with the first. I can successfully send UART data between the two at 2.5M, so if there's a wiring issue, it must be pretty subtle.

My suspicion is that I have to somehow tell LinuxCNC/Mesa to enable the SSERIAL on TB3. Is there a HAL/INI change I should make? A jumper to swap? Forgive my inexperience here - trying to figure this out as I go along.

Thanks again!

**Comment by fdarling** [comment]
PNCConf should generate a LinuxCNC configuration that by default uses all the SmartSerial ports (regardless of whether devices are present). Here is the relevant line from the generated `.hal` file for a 7i92 + 7i76:

```
loadrt hm2_eth board_ip="192.168.1.121" config=" num_encoders=0 num_pwmgens=0 num_stepgens=5 sserial_port_0=00xxxx"
```

With the relevant option being `sserial_port_0=00xxxx`, which means use the first two smart serial "channels" for instance 0, and both in mode "0". The documentation for this is here (search for sserial_port_N):

http://linuxcnc.org/docs/2.6/html/man/man9/hostmot2.9.html#config%20modparam

Make sure the `#define SHOW_VERBOSE` line is uncommented:

https://github.com/fdarling/mesa-smartserial-device-template/blob/a29ee45c41fa3f7d7e5b37cf8b2d2a77e05f2472/Mesa_SmartSerial_Device_Template_Project/Mesa_SmartSerial_Device_Template_Project.ino#L141

The Teensy will log any incoming UART traffic over the USB virtual serial port. If you aren't seeing anything whatsoever, and you indeed have the channels enabled in the LinuxCNC HostMot2 driver, then something is probably wired incorrectly. Perhaps you have RX/TX backwards, or perhaps you have the entire RJ45 pinout wrong as there are two different wiring standards: T-568A and T-568B, with Mesa using the "B" standard. Double check their documentation:

http://www.mesanet.com/pdf/parallel/7i76eman.pdf#page=20

Please post the output of `mesaflash --readhmid --device 7i76e --addr 192.168.1.121` (or whichever IP address) to make sure that you have enough SmartSerial capable pins, and also please post your `loadrt hm2_eth` line from your generated HAL file.

For reference, here is the output for a 7i92 + 7i76:

<details><summary>(click to show mesaflash output)</summary>
<p>

```
$ mesaflash --readhmid --device 7i92 --addr 192.168.1.121
Configuration Name: HOSTMOT2

General configuration information:

  BoardName : MESA7I92
  FPGA Size: 9 KGates
  FPGA Pins: 144
  Number of IO Ports: 2
  Width of one I/O port: 17
  Clock Low frequency: 100.0000 MHz
  Clock High frequency: 200.0000 MHz
  IDROM Type: 3
  Instance Stride 0: 4
  Instance Stride 1: 64
  Register Stride 0: 256
  Register Stride 1: 256

Modules in configuration:

  Module: DPLL
  There are 1 of DPLL in configuration
  Version: 0
  Registers: 7
  BaseAddress: 7000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

  Module: WatchDog
  There are 1 of WatchDog in configuration
  Version: 0
  Registers: 3
  BaseAddress: 0C00
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

  Module: IOPort
  There are 2 of IOPort in configuration
  Version: 0
  Registers: 5
  BaseAddress: 1000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

  Module: QCount
  There are 1 of QCount in configuration
  Version: 2
  Registers: 5
  BaseAddress: 3000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

  Module: SSerial
  There are 1 of SSerial in configuration
  Version: 0
  Registers: 6
  BaseAddress: 5B00
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 64 bytes

  Module: StepGen
  There are 5 of StepGen in configuration
  Version: 2
  Registers: 10
  BaseAddress: 2000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

  Module: LED
  There are 1 of LED in configuration
  Version: 0
  Registers: 1
  BaseAddress: 0200
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes

Configuration pin-out:

IO Connections for P2
Pin#  I/O   Pri. func    Sec. func       Chan      Pin func        Pin Dir

 1      0   IOPort       StepGen          0        Dir/Table2      (Out)
14      1   IOPort       StepGen          0        Step/Table1     (Out)
 2      2   IOPort       StepGen          1        Dir/Table2      (Out)
15      3   IOPort       StepGen          1        Step/Table1     (Out)
 3      4   IOPort       StepGen          2        Dir/Table2      (Out)
16      5   IOPort       StepGen          2        Step/Table1     (Out)
 4      6   IOPort       StepGen          3        Dir/Table2      (Out)
17      7   IOPort       StepGen          3        Step/Table1     (Out)
 5      8   IOPort       StepGen          4        Dir/Table2      (Out)
 6      9   IOPort       StepGen          4        Step/Table1     (Out)
 7     10   IOPort       SSerial          0        TXData0         (Out)
 8     11   IOPort       SSerial          0        RXData0         (In)
 9     12   IOPort       SSerial          0        TXData1         (Out)
10     13   IOPort       SSerial          0        RXData1         (In)
11     14   IOPort       QCount           0        Quad-IDX        (In)
12     15   IOPort       QCount           0        Quad-B          (In)
13     16   IOPort       QCount           0        Quad-A          (In)

IO Connections for P1
Pin#  I/O   Pri. func    Sec. func       Chan      Pin func        Pin Dir

 1     17   IOPort       None           
14     18   IOPort       None           
 2     19   IOPort       None           
15     20   IOPort       None           
 3     21   IOPort       None           
16     22   IOPort       None           
 4     23   IOPort       None           
17     24   IOPort       None           
 5     25   IOPort       None           
 6     26   IOPort       None           
 7     27   IOPort       None           
 8     28   IOPort       None           
 9     29   IOPort       None           
10     30   IOPort       None           
11     31   IOPort       None           
12     32   IOPort       None           
13     33   IOPort       None
```

</p>
</details>

**Comment by fdarling** [comment]
I forgot to mention, you can also use `mesaflash` to list all connected SmartSerial devices, which is a lot faster / simpler for the initial testing:

```
mesaflash --sserial --device 7i76e --addr 192.168.1.121
```

Here is example output for my 7i92 + 7i76:

```
$ mesaflash --sserial --device 7i92 --addr 192.168.1.121
SSLBP port 0:
  SSLBP Version: 1.43
  SSLBP Channels: 2
  SSLBP Baud Rate: 2500000
  sserial device at channel 0: 7I76 GPIO+SPINDLE (unit 0x100008C4)
    SwRevision = 14
    HwRevision = 1
    NVBaudRate = 2.5Mb
    NVUnitNumber = 0x100008C4
    NVWatchDogTimeout = 50ms
    SOFTWARE MODE IO_Spin [index 00]
    SOFTWARE MODE IO_Ana_Spin [index 01]
    SOFTWARE MODE IO_Enc_Ana_Spin_FV [index 02]
```

Even if that doesn't show any output, it should still be probing, so you'd expect UART traffic to the Teensy.

**Comment by RaphiePS** [comment]
Hey, thank you for such a phenomenally fast and thorough response. Amazing. 

Here's `mesaflash --serial`:

```
$ mesaflash --sserial --device 7i76e --addr 10.10.10.10
SSLBP port 0:
  SSLBP Version: 1.43
  SSLBP Channels: 2
  SSLBP Baud Rate: 2500000
  sserial device at channel 0: 7I76 (unit 0x1A0008D7)
    SwRevision = 15
    HwRevision = 1
    NVBaudRate = 2.5Mb
    NVUnitNumber = 0x1A0008D7
    NVWatchDogTimeout = 50ms
    SOFTWARE MODE IO_Spin [index 00]
    SOFTWARE MODE IO_Ana_Spin [index 01]
    SOFTWARE MODE IO_Enc_Ana_Spin_FV [index 02]
```

And then `mesaflash --readhmid`:

```
$ mesaflash --readhmid --device 7i76e --addr 10.10.10.10
Configuration Name: HOSTMOT2
 
General configuration information:
 
  BoardName : MESA7I76
  FPGA Size: 16 KGates
  FPGA Pins: 256
  Number of IO Ports: 3
  Width of one I/O port: 17
  Clock Low frequency: 100.0000 MHz
  Clock High frequency: 200.0000 MHz
  IDROM Type: 3
  Instance Stride 0: 4
  Instance Stride 1: 64
  Register Stride 0: 256
  Register Stride 1: 256
 
Modules in configuration:
 
  Module: DPLL
  There are 1 of DPLL in configuration
  Version: 0
  Registers: 7
  BaseAddress: 7000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
  Module: WatchDog
  There are 1 of WatchDog in configuration
  Version: 0
  Registers: 3
  BaseAddress: 0C00
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
  Module: IOPort
  There are 3 of IOPort in configuration
  Version: 0
  Registers: 5
  BaseAddress: 1000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
  Module: StepGen
  There are 5 of StepGen in configuration
  Version: 2
  Registers: 10
  BaseAddress: 2000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
  Module: QCount
  There are 1 of QCount in configuration
  Version: 2
  Registers: 5
  BaseAddress: 3000
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
  Module: SSerial
  There are 1 of SSerial in configuration
  Version: 0
  Registers: 6
  BaseAddress: 5B00
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 64 bytes
 
  Module: LED
  There are 1 of LED in configuration
  Version: 0
  Registers: 1
  BaseAddress: 0200
  ClockFrequency: 100.000 MHz
  Register Stride: 256 bytes
  Instance Stride: 4 bytes
 
Configuration pin-out:
 
IO Connections for on-card
Pin#  I/O   Pri. func    Sec. func       Chan      Pin func        Pin Dir
 
 1      0   IOPort       StepGen          0        Dir/Table2      (Out)
14      1   IOPort       StepGen          0        Step/Table1     (Out)
 2      2   IOPort       StepGen          1        Dir/Table2      (Out)
15      3   IOPort       StepGen          1        Step/Table1     (Out)
 3      4   IOPort       StepGen          2        Dir/Table2      (Out)
16      5   IOPort       StepGen          2        Step/Table1     (Out)
 4      6   IOPort       StepGen          3        Dir/Table2      (Out)
17      7   IOPort       StepGen          3        Step/Table1     (Out)
 5      8   IOPort       StepGen          4        Dir/Table2      (Out)
 6      9   IOPort       StepGen          4        Step/Table1     (Out)
 7     10   IOPort       SSerial          0        TXData0         (Out)
 8     11   IOPort       SSerial          0        RXData0         (In)
 9     12   IOPort       SSerial          0        TXData1         (Out)
10     13   IOPort       SSerial          0        RXData1         (In)
11     14   IOPort       QCount           0        Quad-IDX        (In)
12     15   IOPort       QCount           0        Quad-B          (In)
13     16   IOPort       QCount           0        Quad-A          (In)
 
IO Connections for P1
Pin#  I/O   Pri. func    Sec. func       Chan      Pin func        Pin Dir
 
 1     17   IOPort       None           
14     18   IOPort       None           
 2     19   IOPort       None           
15     20   IOPort       None           
 3     21   IOPort       None           
16     22   IOPort       None           
 4     23   IOPort       None           
17     24   IOPort       None           
 5     25   IOPort       None           
 6     26   IOPort       None           
 7     27   IOPort       None           
 8     28   IOPort       None           
 9     29   IOPort       None           
10     30   IOPort       None           
11     31   IOPort       None           
12     32   IOPort       None           
13     33   IOPort       None           
 
IO Connections for P2
Pin#  I/O   Pri. func    Sec. func       Chan      Pin func        Pin Dir
 
 1     34   IOPort       None           
14     35   IOPort       None           
 2     36   IOPort       None           
15     37   IOPort       None           
 3     38   IOPort       None           
16     39   IOPort       None           
 4     40   IOPort       None           
17     41   IOPort       None           
 5     42   IOPort       None           
 6     43   IOPort       None           
 7     44   IOPort       None           
 8     45   IOPort       None           
 9     46   IOPort       None           
10     47   IOPort       None           
11     48   IOPort       None           
12     49   IOPort       None           
13     50   IOPort       None  
```

My `loadrt hm2_eth` line is: 
```
loadrt hm2_eth board_ip="10.10.10.10" config=" num_encoders=1 num_pwmgens=0 num_stepgens=3 sserial_port_0=00xxxx" 
```

Nothing jumps out at me, so this seems like a wiring thing? I've multimeter continuity-tested from the TB3 connector to the pins of the SN75179BP, so I can rule out cabling. Here's how I have it connected, maybe I've misunderstood.

- TB3 **16 (RX+)** to **Z**
- TB3 **17 (RX-)** to **Y**
- TB3 **18 (TX+)** to **A**
- TB3 **19 (TX-)** to **B**

I also tried swapping the polarities, with **RX+** to **Y** and **RX- to Z**, and **TX+ to B** and **TX- to A**. No dice. Maybe this experimenting burned out the Mesa's RS-422 hardware? Yikes. Let me know if you have wiring thoughts!

Finally, the relevant manual pages for quick reference:

![image](https://user-images.githubusercontent.com/1091375/134065544-668cac89-6440-460b-a4be-ab51231b3b81.png)

![image](https://user-images.githubusercontent.com/1091375/134065579-d9fac930-ebb7-4bfc-9576-7110f93e1828.png)

![image](https://user-images.githubusercontent.com/1091375/134066080-8861bd93-9e38-4ff0-aabc-c111a096208c.png)

**Comment by fdarling** [comment]
The RS-422 drivers that are RS-485 capable are quite robust, they will source 250mA of current until they go into thermal shut down, and are tolerant of voltages up to something like 50V. If you are suspicious that they aren't working at all, you can configure the transmit pin as a GPIO and toggle them, seeing if the TX+ and TX- pins invert their polarity (0V <--> 5V).

To be clear, in the default state of the FPGA (and also the resulting state if the watchdog bites because you exited LinuxCNC abruptly) the GPIO are set as inputs with pull-up resistors (according to the 7i92 documentation). This means that they are still effectively outputting a weak HIGH. The RS-422 outputs should be 0V on TX+ and 5V on TX- (I guess it's inverted?).

Create the following HAL script (name it `toggle_tx.hal`):

```
loadrt trivkins coordinates=XYYZ kinstype=BOTH
loadrt motmod servo_period_nsec=1000000 num_joints=4

loadrt hostmot2
loadrt hm2_eth board_ip="192.168.1.121" config=" num_encoders=0 num_pwmgens=0 num_stepgens=5 sserial_port_0=0xxxxx"
setp hm2_7i76e.0.watchdog.timeout_ns 5000000
addf hm2_7i76e.0.read  servo-thread
addf hm2_7i76e.0.write servo-thread

start

setp hm2_7i76e.0.gpio.012.is_output true
setp hm2_7i76e.0.gpio.012.out 0
```

Then run the script using `halrun`:

```
halrun -I toggle_tx.hal
```

If you have a multimeter between GND (TB3 pin 15) and TX+ (TB3 pin 18), you should see it change from 0V to 5V. If that doesn't work, edit the script and change `gpio.012.out 0` to `gpio.012.out 1` to invert how the pin is driven.

If that doesn't work, then either you don't have 5V going to the card (check the voltage between TB3 pin 15 and TB3 pin 20 or maybe pin 21), or you indeed have a dead RS-422 transmitter...

**Comment by RaphiePS** [comment]
It works! I'm finally receiving/sending serial! am not sure which of the following solved it, but one or more of the following steps fixed things:
* Creating a brand new config using Pncconf
* Actually properly exiting LinuxCNC ;)
* Running your script, which did indeed successfully toggle the pins. Nifty!
* Upgrading to LinuxCNC 2.8.2
* Swapping wire polarities for the umpteenth time

The one thing I'm still missing is how I actually interact with this from LinuxCNC. I'm running `halcmd show | grep -i cust` and nothing is turning up. This is despite seeing `LBP_COMMAND_LOCAL_READ_CARD_NAME_CHAR0` / `LBP_COMMAND_RPC_SMARTSERIAL_PROCESS_DATA` in the Teensy's verbose output. I must be missing something conceptually here.

Thank you again so, so much. This is way above and beyond!

**Comment by RaphiePS** [comment]
Redid my wiring, and _everything_ finally works. Turns out 2.5M requires more robust connections than I'm used to with slower baudrates, duh. Thanks for your patience, apologies for the foolishness, and once again bravo for the sample code.
